### ISSUE TITLE
Type 3 - RADAR_SEMIMOBILE_SPEED it's playing sound

### ISSUE THREAD

**Issue by raelgc** [miszellek/SygicOfflineSpeedcams#1]
Hi there! First: thank you for this converter! It works like a charm!

Only minor issue I've noticed is a note in the README file. You said:

> PS: Type 3 - RADAR_SEMIMOBILE_SPEED only show icon, no sound

But in current version, semi-mobile do play a sound!

**Comment by miszellek** [comment]
You're right, they fix it
