### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by dxdydado** [miszellek/SygicOfflineSpeedcams#5]
Hello. Is this project still live or abandoned? i get error in line 449

**Comment by dxdydado** [comment]
or do something wrong?
https://i.postimg.cc/3JQwZcKz/Snap441.png

please update, i will give donation

**Comment by dxdydado** [comment]
please update skript i will donate to you

**Comment by miszellek** [comment]
I made a few changes ... check now

**Comment by dxdydado** [comment]
you are saver!!! tested, working... donation under a way :)

**Comment by dxdydado** [comment]
please give me donation link? paypal?

**Comment by dxdydado** [comment]
found, sorry, excitement :)

**Comment by miszellek** [comment]
It's not really a problem and I'm glad I could help ;)

pon., 29 mar 2021 o 18:22 dxdydado ***@***.***> napisał(a):

**Comment by miszellek** [comment]
THHHHHHHHHHHHHHHHHHHXXXXX very much for your
donation!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

pon., 29 mar 2021 o 18:43 miszel ***@***.***> napisał(a):
